// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1JNtGUKQTDellibloaHu3Z5mWR3VEhUM',
    appId: '1:514319943676:web:d6d317e3f2aeb260901479',
    messagingSenderId: '514319943676',
    projectId: 'quick-chat-95ddb',
    authDomain: 'quick-chat-95ddb-5a515.firebaseapp.com',
    storageBucket: 'quick-chat-95ddb.appspot.com',
    measurementId: 'G-ZGN2212PEJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3aIgP9vFlkvduiVXsGDSVO5aEOX9UHQM',
    appId: '1:514319943676:android:be2b6de3df8e88c8901479',
    messagingSenderId: '514319943676',
    projectId: 'quick-chat-95ddb',
    storageBucket: 'quick-chat-95ddb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2BouwBiBEIMe4vHq7y5N3WXh9MSwAEZs',
    appId: '1:514319943676:ios:4d24aae04e824af3901479',
    messagingSenderId: '514319943676',
    projectId: 'quick-chat-95ddb',
    storageBucket: 'quick-chat-95ddb.appspot.com',
    iosBundleId: 'com.example.quickChat',
  );
}
